### ISSUE TITLE
Type error in github call

### ISSUE THREAD

**Issue by imalsogreg** [shapr/fermatslastmargin#1]
I'm doing a `cabal new-run` with `ghc-8.4` and `github-0.19`

```
src/Lib.hs:(291,14)-(294,23): error:
    • Couldn't match expected type ‘ValueSpec GithubConfig’
                  with actual type ‘ValueSpecs GithubConfig’
    • In the expression:
        sectionsSpec "github"
          $ do username <- reqSection "username" "GitHub username"
               oauth <- reqSection "oauth" "OAuth Token for GitHub"
               return GC {..}
      In an equation for ‘githubSpec’:
          githubSpec
            = sectionsSpec "github"
                $ do username <- reqSection "username" "GitHub username"
                     oauth <- reqSection "oauth" "OAuth Token for GitHub"
                     return GC {..}
    |
291 | githubSpec = sectionsSpec "github" $
    |              ^^^^^^^^^^^^^^^^^^^^^^^...
```

**Comment by imalsogreg** [comment]
It works with `github-0.22` - I'll make a PR with a lower version bound after the code moves from `spookel` (unless you get to it first)

**Comment by shapr** [comment]
Wow, you found this!
I'm building the actual code in a my spookel repository, I'll have it moved to here before Halloween.
So, try out http://github.com/shapr/spookel for the next week!

**Comment by shapr** [comment]
You convinced me to move the code from spookel to this repo, it's done! Feel free to put up a PR!

**Comment by imalsogreg** [comment]
Oops - I hope I didn't do some issues/PRs while the repo was meant to be hidden!

**Comment by shapr** [comment]
It's all good, this has to be released by Halloween!
