### ISSUE TITLE
one single paper list filter field

### ISSUE THREAD

**Issue by shapr** [shapr/fermatslastmargin#16]
filter viewed papers by whatever string is in the filter box, rather than per-column filter

**Comment by solomon-b** [comment]
I would like to take a stab at this. Do you have any suggestions about where to start diving into the code base?

**Comment by shapr** [comment]
Howdy Solomon!
The state is described here: https://github.com/shapr/fermatslastmargin/blob/master/src/Lib.hs#L54

readState produces a map from DOI to paper: https://github.com/shapr/fermatslastmargin/blob/master/src/Lib.hs#L86

I suspect you could create a filter endpoint and POST the text to something that filters all of [Paper] in FLMState ?

If you have any questions I'm happy to help or chat.

**Comment by chessai** [comment]
nice

**Comment by solomon-b** [comment]
Thanks @shapr! I'll see what I can do this week.

**Comment by shapr** [comment]
fixed by #42
